export const sampleEvents1: PalestrinhaEvent[] = [
  {
    publicId: "ABC123",
    name: "Tech Conference 2023",
    description:
      "A conference focused on the latest advancements in technology.",
    eventType: "EventoAcademico",
    urlMoreInfo: "https://example.com/tech-conference",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Tech Events Inc.",
    majorEvent: "Technology",
    relatedSubAreas: ["Artificial Intelligence", "Blockchain", "Cybersecurity"],
    startDate: "2023-09-15T00:00:00.000Z",
    endDate: "2023-09-17T23:59:59.999Z",
  },
  {
    publicId: "DEF456",
    name: "Art Exhibition",
    description: "An exhibition showcasing contemporary art pieces.",
    eventType: "EventoCultural",
    urlMoreInfo: "https://example.com/art-exhibition",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Art Gallery",
    majorEvent: "Art",
    relatedSubAreas: ["Painting", "Sculpture", "Photography"],
    startDate: "2023-10-20T10:00:00.000Z",
    endDate: "2023-10-31T18:00:00.000Z",
  },
  {
    publicId: "GHI789",
    name: "Music Festival",
    description:
      "A three-day music festival featuring various genres and artists.",
    eventType: "EventoCultural",
    urlMoreInfo: "https://example.com/music-festival",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Music Events Co.",
    majorEvent: "Music",
    relatedSubAreas: ["Rock", "Pop", "EDM"],
    startDate: "2023-07-15T12:00:00.000Z",
    endDate: "2023-07-17T23:59:59.999Z",
  },
  {
    publicId: "JKL012",
    name: "Science Symposium",
    description:
      "An academic symposium discussing recent scientific discoveries.",
    eventType: "EventoAcademico",
    urlMoreInfo: "https://example.com/science-symposium",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Science Institute",
    majorEvent: "Science",
    relatedSubAreas: ["Physics", "Biology", "Chemistry"],
    startDate: "2023-11-05T09:00:00.000Z",
    endDate: "2023-11-07T17:00:00.000Z",
  },
  {
    publicId: "MNO345",
    name: "Film Festival",
    description: "A week-long film festival showcasing international cinema.",
    eventType: "EventoCultural",
    urlMoreInfo: "https://example.com/film-festival",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Film Society",
    majorEvent: "Film",
    relatedSubAreas: ["Drama", "Comedy", "Documentary"],
    startDate: "2023-09-25T10:00:00.000Z",
    endDate: "2023-10-01T23:59:59.999Z",
  },
  {
    publicId: "PQR678",
    name: "Business Conference",
    description: "A conference for entrepreneurs and business professionals.",
    eventType: "EventoAcademico",
    urlMoreInfo: "https://example.com/business-conference",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Business Events Corp.",
    majorEvent: "Business",
    relatedSubAreas: ["Entrepreneurship", "Finance", "Marketing"],
    startDate: "2023-08-10T09:00:00.000Z",
    endDate: "2023-08-12T18:00:00.000Z",
  },
  {
    publicId: "STU901",
    name: "Fashion Show",
    description: "A high-profile fashion show featuring renowned designers.",
    eventType: "EventoCultural",
    urlMoreInfo: "https://example.com/fashion-show",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Fashion Events Agency",
    majorEvent: "Fashion",
    relatedSubAreas: ["Haute Couture", "Streetwear", "Accessories"],
    startDate: "2023-11-18T19:00:00.000Z",
    endDate: "2023-11-20T22:00:00.000Z",
  },
  {
    publicId: "VWX234",
    name: "Literary Conference",
    description: "A conference for writers and literature enthusiasts.",
    eventType: "EventoAcademico",
    urlMoreInfo: "https://example.com/literary-conference",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Literary Society",
    majorEvent: "Literature",
    relatedSubAreas: ["Fiction", "Poetry", "Non-fiction"],
    startDate: "2023-10-05T09:00:00.000Z",
    endDate: "2023-10-07T17:00:00.000Z",
  },
  {
    publicId: "YZA567",
    name: "Food Festival",
    description:
      "A culinary festival celebrating diverse cuisines and flavors.",
    eventType: "EventoCultural",
    urlMoreInfo: "https://example.com/food-festival",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Food Events Ltd.",
    majorEvent: "Food",
    relatedSubAreas: ["Gourmet", "Street Food", "Baking"],
    startDate: "2023-09-08T12:00:00.000Z",
    endDate: "2023-09-10T22:00:00.000Z",
  },
  {
    publicId: "BCD789",
    name: "Technology Hackathon",
    description: "A weekend-long hackathon for technology enthusiasts.",
    eventType: "EventoAcademico",
    urlMoreInfo: "https://example.com/tech-hackathon",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Tech Hackathons Inc.",
    majorEvent: "Technology",
    relatedSubAreas: [
      "Software Development",
      "Hardware Engineering",
      "Internet of Things",
    ],
    startDate: "2023-11-10T18:00:00.000Z",
    endDate: "2023-11-12T20:00:00.000Z",
  },
  {
    publicId: "EFG901",
    name: "Dance Performance",
    description: "An enchanting dance performance by a renowned dance troupe.",
    eventType: "EventoCultural",
    urlMoreInfo: "https://example.com/dance-performance",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Dance Company",
    majorEvent: "Dance",
    relatedSubAreas: ["Ballet", "Contemporary", "Hip Hop"],
    startDate: "2023-08-25T20:00:00.000Z",
    endDate: "2023-08-27T22:00:00.000Z",
  },
  {
    publicId: "GHI012",
    name: "Medical Conference",
    description:
      "A conference focused on advancements in the field of medicine.",
    eventType: "EventoAcademico",
    urlMoreInfo: "https://example.com/medical-conference",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Medical Association",
    majorEvent: "Medicine",
    relatedSubAreas: ["Cardiology", "Neurology", "Oncology"],
    startDate: "2023-10-15T09:00:00.000Z",
    endDate: "2023-10-17T18:00:00.000Z",
  },
  {
    publicId: "JKL234",
    name: "Comedy Show",
    description: "An evening of laughter with renowned stand-up comedians.",
    eventType: "EventoCultural",
    urlMoreInfo: "https://example.com/comedy-show",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Comedy Central Productions",
    majorEvent: "Comedy",
    relatedSubAreas: ["Stand-up Comedy", "Improv", "Sketch Comedy"],
    startDate: "2023-09-05T19:30:00.000Z",
    endDate: "2023-09-05T22:00:00.000Z",
  },
  {
    publicId: "MNO345",
    name: "Environmental Summit",
    description:
      "A summit focused on environmental conservation and sustainability.",
    eventType: "EventoAcademico",
    urlMoreInfo: "https://example.com/environmental-summit",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Environmental Organization",
    majorEvent: "Environment",
    relatedSubAreas: ["Climate Change", "Renewable Energy", "Conservation"],
    startDate: "2023-11-25T09:00:00.000Z",
    endDate: "2023-11-27T17:00:00.000Z",
  },
  {
    publicId: "PQR456",
    name: "Theater Play",
    description: "A captivating theater play by a renowned theater group.",
    eventType: "EventoCultural",
    urlMoreInfo: "https://example.com/theater-play",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Theater Company",
    majorEvent: "Theater",
    relatedSubAreas: ["Drama", "Comedy", "Musical"],
    startDate: "2023-08-15T19:00:00.000Z",
    endDate: "2023-08-15T21:30:00.000Z",
  },
  {
    publicId: "STU567",
    name: "Educational Workshop",
    description: "A workshop aimed at enhancing teaching methodologies.",
    eventType: "EventoAcademico",
    urlMoreInfo: "https://example.com/educational-workshop",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Education Institute",
    majorEvent: "Education",
    relatedSubAreas: [
      "Pedagogy",
      "Curriculum Development",
      "Educational Technology",
    ],
    startDate: "2023-10-08T10:00:00.000Z",
    endDate: "2023-10-08T16:00:00.000Z",
  },
  {
    publicId: "VWX789",
    name: "Sports Tournament",
    description:
      "A multi-sport tournament showcasing various athletic competitions.",
    eventType: "EventoCultural",
    urlMoreInfo: "https://example.com/sports-tournament",
    urlSubscribe: "https://example.com/subscribe",
    creatorName: "Sports Association",
    majorEvent: "Sports",
    relatedSubAreas: ["Basketball", "Soccer", "Tennis"],
    startDate: "2023-09-22T08:00:00.000Z",
    endDate: "2023-09-24T18:00:00.000Z",
  },
];
